# author: Sahand Kashani <sahand.kashani@epfl.ch>

# LUT
LEN_LUT_BITS = 64

# BRAM
NUM_BRAM_MEMORY_LINES = 64 # [INIT_00 .. INIT_3f]
LEN_BRAM_MEMORY_LINE_BITS = 256
LEN_BRAM_MEMORY_BITS = NUM_BRAM_MEMORY_LINES * LEN_BRAM_MEMORY_LINE_BITS

NUM_BRAM_PARITY_LINES = 8 # [INITP_00 .. INITP_07]
LEN_BRAM_PARITY_LINE_BITS = 256
LEN_BRAM_PARITY_BITS = NUM_BRAM_PARITY_LINES * LEN_BRAM_PARITY_LINE_BITS
